//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Escudeiro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDC.Escudeiro.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Em quais linguagens o C# foi inspirado?.
        /// </summary>
        public static string _00 {
            get {
                return ResourceManager.GetString("00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A criação do C# foi baseada nas linguagens de programação C, C++ e Java. Deste modo, programadores habituados com uma dessas linguagens são capazes de desenvolver soluções sem maiores dificuldades, pois ela reúne recursos de cada uma destas linguagens base e adiciona novos recursos exclusivos. Em relação a linguagem C, o C# tem foco na compilação de soluções de alto nível, já a linguagem C é voltada para o desenvolvimento de baixo nível. Outras comparações, de acordo com MSDN (2012), o C#, simplifica de mod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _000 {
            get {
                return ResourceManager.GetString("000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inicialmente o C# foi criado para qual finalidade?.
        /// </summary>
        public static string _01 {
            get {
                return ResourceManager.GetString("01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O C# surgiu com a finalidade de possibilitar a criação de soluções executáveis sobre a plataforma .NET Framework, com o intuito de flexibilizar o desenvolvimento de aplicativos. Dessa maneira, o desenvolvedor não cria soluções para um dispositivo eletrônico específico, e sim para a plataforma .NET Framework..
        /// </summary>
        public static string _010 {
            get {
                return ResourceManager.GetString("010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Quais os principais motivos para a Microsoft ter migrado para o Core?.
        /// </summary>
        public static string _02 {
            get {
                return ResourceManager.GetString("02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O .NET Framework é usado para desenvolvimento de aplicações Windows usando Windows Forms , WPF e de aplicações Web usando ASP .NET MVC. O .NET Core é open-source e multiplataforma e suporta UWP e as bibliotecas da ASP .NET Core. A UWP é usada para criar aplicação Windows 10 e a ASP .NET Core é usada para criar aplicações Web para Windows, Linux e Mac..
        /// </summary>
        public static string _020 {
            get {
                return ResourceManager.GetString("020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Cite as principais diferenças entre .Net Full Framework e .Net Core..
        /// </summary>
        public static string _03 {
            get {
                return ResourceManager.GetString("03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O principal motivo foi adicionar as seguintes características e torna-lo o sucessor do .Net framework. Primeiramente, a possibilidade de plataforma cruzada entre diferentes sistemas operacionais para uma mesma solução. O .Net Core possui código-fonte aberto, se tornando um software livre. Ele implementa funcionalidades modernas como programação assíncrona e recursos de alto desempenho. Além de fornecer compatibilidade com contêineres do Docker disponibilizando uma implantação flexível..
        /// </summary>
        public static string _030 {
            get {
                return ResourceManager.GetString("030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba os valores A e B. Mostre de forma simples, como utilizar variáveis e manipular dados..
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba nome e salário de N funcionários. Utilize a repetição for e while..
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que imprima todos os múltiplos de 3, entre 1 e 100. Utilize a repetição while..
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba N alunos com suas respectivas notas. Use foreach para a estrutura de repetição..
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que calcule a fórmula de Bhaskara..
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que demonstre a diferença entre REF e OUT..
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que leia 4 números inteiros e calcular a soma dos que forem pares..
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que leia N valores decimais, imprima os valores em ordem crescente e decrescente..
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Utilizando a biblioteca LINQ crie no console e execute.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalhando no Console.
        /// </summary>
        public static string IntroducaoConsole {
            get {
                return ResourceManager.GetString("IntroducaoConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma opção.
        /// </summary>
        public static string IntroducaoOpcoes {
            get {
                return ResourceManager.GetString("IntroducaoOpcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perguntas teóricas de introdução.
        /// </summary>
        public static string IntroducaoTeorica {
            get {
                return ResourceManager.GetString("IntroducaoTeorica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precione ↑ e ↓ para selecionar e Enter para escolher | Precione Esc para sair.
        /// </summary>
        public static string MenuIntroducao {
            get {
                return ResourceManager.GetString("MenuIntroducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precione ↑ e ↓ para selecionar e Enter para escolher | Precione ← para voltar | Precione Esc para sair.
        /// </summary>
        public static string MenuIntroducaoEntrarVoltar {
            get {
                return ResourceManager.GetString("MenuIntroducaoEntrarVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precione ← para voltar | Precione Esc para sair.
        /// </summary>
        public static string MenuIntroducaoVoltar {
            get {
                return ResourceManager.GetString("MenuIntroducaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Validar os exercícios de console.
        /// </summary>
        public static string OpcaoDois {
            get {
                return ResourceManager.GetString("OpcaoDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Validar os exercícios de programação orientada a objetos.
        /// </summary>
        public static string OpcaoTres {
            get {
                return ResourceManager.GetString("OpcaoTres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Respostas sobre a parte teóricas.
        /// </summary>
        public static string OpcaoUm {
            get {
                return ResourceManager.GetString("OpcaoUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-vindo ao território de .Net do Mestre dos Códigos.
        /// </summary>
        public static string Saudacoes {
            get {
                return ResourceManager.GetString("Saudacoes", resourceCulture);
            }
        }
    }
}
