//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Escudeiro.Exercicio.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDC.Escudeiro.Exercicio.Console.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o nome: .
        /// </summary>
        internal static string InserirNome {
            get {
                return ResourceManager.GetString("InserirNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira a nota: .
        /// </summary>
        internal static string InserirNota {
            get {
                return ResourceManager.GetString("InserirNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o número: .
        /// </summary>
        internal static string InserirNumero {
            get {
                return ResourceManager.GetString("InserirNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o {0}° valor: .
        /// </summary>
        internal static string InserirPosicaoValor {
            get {
                return ResourceManager.GetString("InserirPosicaoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o salário: .
        /// </summary>
        internal static string InserirSalario {
            get {
                return ResourceManager.GetString("InserirSalario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o valor {0}: .
        /// </summary>
        internal static string InserirValor {
            get {
                return ResourceManager.GetString("InserirValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista está vazia.
        /// </summary>
        internal static string ListaVazia {
            get {
                return ResourceManager.GetString("ListaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número consultado não foi encontrado..
        /// </summary>
        internal static string NumeroNaoEncontrado {
            get {
                return ResourceManager.GetString("NumeroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os pares não foram encontrados..
        /// </summary>
        internal static string ParesNaoEncontrados {
            get {
                return ResourceManager.GetString("ParesNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Some esses 2 valores.
        /// </summary>
        internal static string Pergunta_0_0 {
            get {
                return ResourceManager.GetString("Pergunta-0-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Faça uma subtração do valor A - B.
        /// </summary>
        internal static string Pergunta_0_1 {
            get {
                return ResourceManager.GetString("Pergunta-0-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Divida o valor B por A.
        /// </summary>
        internal static string Pergunta_0_2 {
            get {
                return ResourceManager.GetString("Pergunta-0-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Multiplique o valor A por B.
        /// </summary>
        internal static string Pergunta_0_3 {
            get {
                return ResourceManager.GetString("Pergunta-0-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Número par ou ímpar.
        /// </summary>
        internal static string Pergunta_0_4 {
            get {
                return ResourceManager.GetString("Pergunta-0-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inserir funcionários.
        /// </summary>
        internal static string Pergunta_1_0 {
            get {
                return ResourceManager.GetString("Pergunta-1-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir o maior salário.
        /// </summary>
        internal static string Pergunta_1_1 {
            get {
                return ResourceManager.GetString("Pergunta-1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir o menor salário.
        /// </summary>
        internal static string Pergunta_1_2 {
            get {
                return ResourceManager.GetString("Pergunta-1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir todos os múltiplos de 3.
        /// </summary>
        internal static string Pergunta_2_0 {
            get {
                return ResourceManager.GetString("Pergunta-2-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inserir aluno.
        /// </summary>
        internal static string Pergunta_3_0 {
            get {
                return ResourceManager.GetString("Pergunta-3-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir todos os alunos com média superior a 7.
        /// </summary>
        internal static string Pergunta_3_1 {
            get {
                return ResourceManager.GetString("Pergunta-3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Receba os valores a, b, c.
        /// </summary>
        internal static string Pergunta_4_0 {
            get {
                return ResourceManager.GetString("Pergunta-4-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Definição do ref.
        /// </summary>
        internal static string Pergunta_5_0 {
            get {
                return ResourceManager.GetString("Pergunta-5-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Definição do out.
        /// </summary>
        internal static string Pergunta_5_1 {
            get {
                return ResourceManager.GetString("Pergunta-5-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Somar os pares.
        /// </summary>
        internal static string Pergunta_6_0 {
            get {
                return ResourceManager.GetString("Pergunta-6-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inserir número.
        /// </summary>
        internal static string Pergunta_7_0 {
            get {
                return ResourceManager.GetString("Pergunta-7-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir em ordem crescente.
        /// </summary>
        internal static string Pergunta_7_1 {
            get {
                return ResourceManager.GetString("Pergunta-7-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir em ordem decrescente.
        /// </summary>
        internal static string Pergunta_7_2 {
            get {
                return ResourceManager.GetString("Pergunta-7-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir todos os números da lista.
        /// </summary>
        internal static string Pergunta_8_0 {
            get {
                return ResourceManager.GetString("Pergunta-8-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir todos os números da lista na ordem crescente.
        /// </summary>
        internal static string Pergunta_8_1 {
            get {
                return ResourceManager.GetString("Pergunta-8-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Retornar apenas o número informado.
        /// </summary>
        internal static string Pergunta_8_10 {
            get {
                return ResourceManager.GetString("Pergunta-8-10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir todos os números da lista na ordem decrescente.
        /// </summary>
        internal static string Pergunta_8_2 {
            get {
                return ResourceManager.GetString("Pergunta-8-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir apenas o primeiro número da lista.
        /// </summary>
        internal static string Pergunta_8_3 {
            get {
                return ResourceManager.GetString("Pergunta-8-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir apenas o ultimo número da lista.
        /// </summary>
        internal static string Pergunta_8_4 {
            get {
                return ResourceManager.GetString("Pergunta-8-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inserir um número no início da lista.
        /// </summary>
        internal static string Pergunta_8_5 {
            get {
                return ResourceManager.GetString("Pergunta-8-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Inserir um número no final da lista.
        /// </summary>
        internal static string Pergunta_8_6 {
            get {
                return ResourceManager.GetString("Pergunta-8-6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Remover o primeiro número.
        /// </summary>
        internal static string Pergunta_8_7 {
            get {
                return ResourceManager.GetString("Pergunta-8-7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Remover o último número.
        /// </summary>
        internal static string Pergunta_8_8 {
            get {
                return ResourceManager.GetString("Pergunta-8-8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Retornar apenas os números pares.
        /// </summary>
        internal static string Pergunta_8_9 {
            get {
                return ResourceManager.GetString("Pergunta-8-9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de A + B = {0}.
        /// </summary>
        internal static string Resposta_0_0 {
            get {
                return ResourceManager.GetString("Resposta-0-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de A - B = {0}.
        /// </summary>
        internal static string Resposta_0_1 {
            get {
                return ResourceManager.GetString("Resposta-0-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de B / A = {0}.
        /// </summary>
        internal static string Resposta_0_2 {
            get {
                return ResourceManager.GetString("Resposta-0-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de A * B = {0}.
        /// </summary>
        internal static string Resposta_0_3 {
            get {
                return ResourceManager.GetString("Resposta-0-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor A: {0} {1}, Valor B: {2} {3}.
        /// </summary>
        internal static string Resposta_0_4 {
            get {
                return ResourceManager.GetString("Resposta-0-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionario nome: {0}, salário: {1} inserido.
        /// </summary>
        internal static string Resposta_1_0 {
            get {
                return ResourceManager.GetString("Resposta-1-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O maior salário é: {0}.
        /// </summary>
        internal static string Resposta_1_1 {
            get {
                return ResourceManager.GetString("Resposta-1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O menor salário é: {0}.
        /// </summary>
        internal static string Resposta_1_2 {
            get {
                return ResourceManager.GetString("Resposta-1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é múltiplo de 3.
        /// </summary>
        internal static string Resposta_2_0 {
            get {
                return ResourceManager.GetString("Resposta-2-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno nome: {0}, nota: {1} inserido.
        /// </summary>
        internal static string Resposta_3_0 {
            get {
                return ResourceManager.GetString("Resposta-3-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno nome: {0}, nota: {1}.
        /// </summary>
        internal static string Resposta_3_1 {
            get {
                return ResourceManager.GetString("Resposta-3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raiz X&apos; é: {0} e a raiz X&apos;&apos; é: {1}.
        /// </summary>
        internal static string Resposta_4_0 {
            get {
                return ResourceManager.GetString("Resposta-4-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usado para indicar que o parâmetro passado pode ser modificado pelo método. Por padrão, um tipo de referência passado para um método terá todas as alterações feitas em seus valores refletidas fora do método também. Se você atribuir o tipo de referência a um novo tipo de referência dentro do método, essas alterações serão apenas locais para o método..
        /// </summary>
        internal static string Resposta_5_0 {
            get {
                return ResourceManager.GetString("Resposta-5-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usado para indicar que o parâmetro passado deve ser modificado pelo método. Usando o modificador out, inicializamos uma variável dentro do método. Como ref, tudo o que acontece no método altera a variável fora do método. Com ref, você tem a opção de não fazer alterações no parâmetro. Ao usar out, você deve inicializar o parâmetro que passa dentro do método..
        /// </summary>
        internal static string Resposta_5_1 {
            get {
                return ResourceManager.GetString("Resposta-5-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A soma dos números pares é: {0}.
        /// </summary>
        internal static string Resposta_6_0 {
            get {
                return ResourceManager.GetString("Resposta-6-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número(s) par(es): {0}.
        /// </summary>
        internal static string Resposta_6_1 {
            get {
                return ResourceManager.GetString("Resposta-6-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número: {0} inserido.
        /// </summary>
        internal static string Resposta_7_0 {
            get {
                return ResourceManager.GetString("Resposta-7-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem crescente : {0}.
        /// </summary>
        internal static string Resposta_7_1 {
            get {
                return ResourceManager.GetString("Resposta-7-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem decrescente : {0}.
        /// </summary>
        internal static string Resposta_7_2 {
            get {
                return ResourceManager.GetString("Resposta-7-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos valores inseridos: {0}.
        /// </summary>
        internal static string Resposta_8_0 {
            get {
                return ResourceManager.GetString("Resposta-8-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem crescente : {0}.
        /// </summary>
        internal static string Resposta_8_1 {
            get {
                return ResourceManager.GetString("Resposta-8-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número encontrado é : {0}.
        /// </summary>
        internal static string Resposta_8_10 {
            get {
                return ResourceManager.GetString("Resposta-8-10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem decrescente : {0}.
        /// </summary>
        internal static string Resposta_8_2 {
            get {
                return ResourceManager.GetString("Resposta-8-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro número da lista : {0}.
        /// </summary>
        internal static string Resposta_8_3 {
            get {
                return ResourceManager.GetString("Resposta-8-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimo número da lista : {0}.
        /// </summary>
        internal static string Resposta_8_4 {
            get {
                return ResourceManager.GetString("Resposta-8-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número(s) par(es) {0}.
        /// </summary>
        internal static string Resposta_8_9 {
            get {
                return ResourceManager.GetString("Resposta-8-9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba os valores A e B. Mostre de forma simples, como utilizar variáveis e manipular dados..
        /// </summary>
        internal static string Titulo_0 {
            get {
                return ResourceManager.GetString("Titulo-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba nome e salário de N funcionários. Utilize a repetição for e while..
        /// </summary>
        internal static string Titulo_1 {
            get {
                return ResourceManager.GetString("Titulo-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que imprima todos os múltiplos de 3, entre 1 e 100. Utilize a repetição while..
        /// </summary>
        internal static string Titulo_2 {
            get {
                return ResourceManager.GetString("Titulo-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que receba N alunos com suas respectivas notas. Use foreach para a estrutura de repetição..
        /// </summary>
        internal static string Titulo_3 {
            get {
                return ResourceManager.GetString("Titulo-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que calcule a fórmula de Bhaskara..
        /// </summary>
        internal static string Titulo_4 {
            get {
                return ResourceManager.GetString("Titulo-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que demonstre a diferença entre REF e OUT..
        /// </summary>
        internal static string Titulo_5 {
            get {
                return ResourceManager.GetString("Titulo-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que leia 4 números inteiros e calcular a soma dos que forem pares..
        /// </summary>
        internal static string Titulo_6 {
            get {
                return ResourceManager.GetString("Titulo-6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma aplicação que leia N valores decimais, imprima os valores em ordem crescente e decrescente..
        /// </summary>
        internal static string Titulo_7 {
            get {
                return ResourceManager.GetString("Titulo-7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Utilizando a biblioteca LINQ crie no console e execute..
        /// </summary>
        internal static string Titulo_8 {
            get {
                return ResourceManager.GetString("Titulo-8", resourceCulture);
            }
        }
    }
}
