//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Escudeiro.Exercicio.POO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDC.Escudeiro.Exercicio.POO.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Corrente.
        /// </summary>
        internal static string ContaCorrente {
            get {
                return ResourceManager.GetString("ContaCorrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Especial.
        /// </summary>
        internal static string ContaEspecial {
            get {
                return ResourceManager.GetString("ContaEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conta não foi criada..
        /// </summary>
        internal static string ContaNaoCriada {
            get {
                return ResourceManager.GetString("ContaNaoCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O controle não foi criado..
        /// </summary>
        internal static string ControleNaoCriado {
            get {
                return ResourceManager.GetString("ControleNaoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira a altura: .
        /// </summary>
        internal static string InserirAltura {
            get {
                return ResourceManager.GetString("InserirAltura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o número do canal: .
        /// </summary>
        internal static string InserirCanal {
            get {
                return ResourceManager.GetString("InserirCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira a data de nascimento (dd/MM/yyyy): .
        /// </summary>
        internal static string InserirData {
            get {
                return ResourceManager.GetString("InserirData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o limite: .
        /// </summary>
        internal static string InserirLimite {
            get {
                return ResourceManager.GetString("InserirLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o nome: .
        /// </summary>
        internal static string InserirNome {
            get {
                return ResourceManager.GetString("InserirNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o número da conta: .
        /// </summary>
        internal static string InserirNumeroConta {
            get {
                return ResourceManager.GetString("InserirNumeroConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o saldo inicial: .
        /// </summary>
        internal static string InserirSaldo {
            get {
                return ResourceManager.GetString("InserirSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira a taxa de operação (0 a 100): .
        /// </summary>
        internal static string InserirTaxaOperacao {
            get {
                return ResourceManager.GetString("InserirTaxaOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o tipo da conta: .
        /// </summary>
        internal static string InserirTipoConta {
            get {
                return ResourceManager.GetString("InserirTipoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o tipo do controle: .
        /// </summary>
        internal static string InserirTipoControle {
            get {
                return ResourceManager.GetString("InserirTipoControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o valor: .
        /// </summary>
        internal static string InserirValor {
            get {
                return ResourceManager.GetString("InserirValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Incluir a pessoa.
        /// </summary>
        internal static string Pergunta_1_0 {
            get {
                return ResourceManager.GetString("Pergunta-1-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Calcular a idade.
        /// </summary>
        internal static string Pergunta_1_1 {
            get {
                return ResourceManager.GetString("Pergunta-1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Imprimir dados.
        /// </summary>
        internal static string Pergunta_1_2 {
            get {
                return ResourceManager.GetString("Pergunta-1-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Criar uma conta.
        /// </summary>
        internal static string Pergunta_2_0 {
            get {
                return ResourceManager.GetString("Pergunta-2-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Depositar.
        /// </summary>
        internal static string Pergunta_2_1 {
            get {
                return ResourceManager.GetString("Pergunta-2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Sacar.
        /// </summary>
        internal static string Pergunta_2_2 {
            get {
                return ResourceManager.GetString("Pergunta-2-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Criar controle.
        /// </summary>
        internal static string Pergunta_3_0 {
            get {
                return ResourceManager.GetString("Pergunta-3-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Aumentar volume.
        /// </summary>
        internal static string Pergunta_3_1 {
            get {
                return ResourceManager.GetString("Pergunta-3-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Diminuir volume.
        /// </summary>
        internal static string Pergunta_3_2 {
            get {
                return ResourceManager.GetString("Pergunta-3-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Aumentar número canal.
        /// </summary>
        internal static string Pergunta_3_3 {
            get {
                return ResourceManager.GetString("Pergunta-3-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Diminuir número canal.
        /// </summary>
        internal static string Pergunta_3_4 {
            get {
                return ResourceManager.GetString("Pergunta-3-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Ir para o canal.
        /// </summary>
        internal static string Pergunta_3_5 {
            get {
                return ResourceManager.GetString("Pergunta-3-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade é: {0}.
        /// </summary>
        internal static string Resposta_1_0 {
            get {
                return ResourceManager.GetString("Resposta-1-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de operação: {0}.
        /// </summary>
        internal static string TaxaDeOperacao {
            get {
                return ResourceManager.GetString("TaxaDeOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de conta (0) - Corrente | (1) - Especial.
        /// </summary>
        internal static string TipoConta {
            get {
                return ResourceManager.GetString("TipoConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de controle (0) - Direto na TV | (1) - Remoto.
        /// </summary>
        internal static string TipoControle {
            get {
                return ResourceManager.GetString("TipoControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma classe para representar uma pessoa..
        /// </summary>
        internal static string Titulo_0 {
            get {
                return ResourceManager.GetString("Titulo-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Faça uma aplicação bancária..
        /// </summary>
        internal static string Titulo_1 {
            get {
                return ResourceManager.GetString("Titulo-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) Crie uma classe Televisao e uma classe ControleRemoto que pode controlar o volume e trocar os canais da televisão..
        /// </summary>
        internal static string Titulo_2 {
            get {
                return ResourceManager.GetString("Titulo-2", resourceCulture);
            }
        }
    }
}
